version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Install phase - Installing dependencies"
      - ls -al  # 현재 디렉토리의 파일 목록 표시
      - gradle wrapper  # Gradle Wrapper 초기화
      - chmod +x gradlew
      - ./gradlew assemble

artifacts:
  files:
    - '**/*'
  name: your-build-artifact
  discard-paths: yes